import os
import requests
import base64
from dotenv import load_dotenv
load_dotenv()

class GeminiImageService:
    def __init__(self):
        self.api_key = os.environ.get("GEMINI_API_KEY")
        if not self.api_key:
            raise ValueError("GEMINI_API_KEY environment variable is not set")

    def _optimize_prompt(self, prompt: str) -> str:
        base_prompt = prompt.strip().rstrip('.')
        return (
            f"{base_prompt}. Create exactly one centered subject for 3D reconstruction. "
            "Show the full object clearly in frame as a studio product render from a slightly elevated front three-quarter angle. "
            "Use a plain clean background, soft even lighting, crisp silhouette, rich surface detail, and no occlusion on the main subject. "
            "No extra props, no scenery, no hands, no text, no labels, no frame, and no second object."
        )

    def generate_image(self, prompt: str, output_name: str) -> str:
        """
        Generates an image using Google's Imagen model via REST API and saves it as a PNG file.
        """
        # Define output directory relative to backend root
        base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        outputs_dir = os.path.abspath(os.path.join(base_dir, "outputs"))
        os.makedirs(outputs_dir, exist_ok=True)

        if not output_name.lower().endswith(".png"):
            output_name += ".png"
            
        output_path = os.path.join(outputs_dir, output_name)

        # Generate image using Google's Imagen 4 model via REST API
        url = f"https://generativelanguage.googleapis.com/v1beta/models/imagen-4.0-generate-001:predict?key={self.api_key}"
        headers = {"Content-Type": "application/json"}
        optimized_prompt = self._optimize_prompt(prompt)
        data = {
            "instances": [{"prompt": optimized_prompt}],
            "parameters": {"sampleCount": 1}
        }
        
        response = requests.post(url, headers=headers, json=data)
        
        if response.status_code != 200:
            raise RuntimeError(f"API Error: {response.status_code} - {response.text}")
            
        response_json = response.json()
        predictions = response_json.get('predictions', [])
        
        if not predictions:
            raise RuntimeError("No image was generated by the API.")

        image_b64 = predictions[0].get('bytesBase64Encoded')
        
        if not image_b64:
             raise RuntimeError("No image bytes returned by the API.")

        # Decode base64 and save the image
        image_bytes = base64.b64decode(image_b64)
        with open(output_path, "wb") as f:
            f.write(image_bytes)

        return output_path
