import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';

import { compileSemanticDraft } from '../scripts/compile-semantic-draft.mjs';

test('compileSemanticDraft rejects 3D experiment drafts without a recipe', async () => {
  const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'chem-compile-'));
  await assert.rejects(
    compileSemanticDraft({
      slug: 'litmus-acid-base',
      draftsDir: tempDir,
      draft: {
        kind: 'experiment',
        topic: 'Giấy quỳ tím thử axit và bazơ',
        level: 'THCS',
        skill: 'chem-3d-experiment',
        language: 'vi',
        renderMode: 'threejs',
        scene: {
          apparatus: ['litmus-paper', 'reagent-bottle', 'beaker'],
          cameraPreset: 'bench-3qtr',
          themeVersion: 'chem-lab-v1',
        },
        interaction: {
          primaryMode: 'direct-manipulation',
          goldenPath: ['pick-litmus', 'touch-solution', 'observe-color'],
          resetRequired: true,
          autoplayRequired: true,
        },
        verification: {
          requiresFormat: true,
          requiresSmoke: true,
          requiresCanvas: true,
          requiresInteraction: true,
          requiresVisibility: true,
          requiresOffline: true,
        },
      },
    }),
    /3D experiment drafts require semantic-draft\.json\.recipe/
  );
});

test('compileSemanticDraft supports the iron nail in CuSO4 experiment route', async () => {
  const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'chem-compile-cuso4-'));
  const output = await compileSemanticDraft({
    slug: 'iron-nail-cuso4-displacement',
    draftsDir: tempDir,
    draft: {
      kind: 'experiment',
      recipe: 'iron-cuso4-displacement',
      topic: 'Đinh sắt thả vào dung dịch CuSO4',
      level: 'THCS',
      skill: 'chem-3d-experiment',
      language: 'vi',
      renderMode: 'threejs',
      scene: {
        apparatus: ['iron-nail', 'beaker'],
        cameraPreset: 'lab-close',
        themeVersion: 'chem-lab-dark',
      },
      interaction: {
        primaryMode: 'direct-manipulation',
        goldenPath: ['place-iron', 'observe-copper-coating', 'finish-reaction'],
        resetRequired: true,
        autoplayRequired: true,
      },
      verification: {
        requiresFormat: true,
        requiresSmoke: true,
        requiresCanvas: true,
        requiresInteraction: true,
        requiresVisibility: true,
        requiresOffline: true,
      },
    },
  });

  const hud = await fs.readFile(path.join(output.draftsDir, 'iron-nail-cuso4-displacement.hud.html'), 'utf8');
  const scene = await fs.readFile(path.join(output.draftsDir, 'iron-nail-cuso4-displacement.scene.js'), 'utf8');
  const meta = JSON.parse(
    await fs.readFile(path.join(output.draftsDir, 'iron-nail-cuso4-displacement.meta.json'), 'utf8')
  );

  assert.match(hud, /Đinh sắt thả vào dung dịch CuSO4/);
  assert.match(hud, /id="statusText"/);
  assert.match(hud, /data-action="autoplay"/);
  assert.match(scene, /@generated by scripts\/build-recipe-scene\.mjs/);
  assert.match(scene, /createIronNailApparatus/);
  assert.match(scene, /createBeakerApparatus/);
  assert.match(scene, /createFreeDragController/);
  assert.match(scene, /getStepContract\(\)/);
  assert.match(scene, /"place-iron"/);
  assert.match(scene, /"finish-reaction"/);
  assert.equal(meta.skill, 'chem-3d-experiment');
  assert.equal(meta.themeVersion, 'chem-lab-dark');
  assert.equal(meta.recipe, 'iron-cuso4-displacement');
  assert.equal(meta.generatedBy, 'recipe-scene-builder');
});

test('compileSemanticDraft rejects recipe drafts without recipe-scene-builder support', async () => {
  const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'chem-compile-recipe-'));
  await assert.rejects(
    compileSemanticDraft({
      slug: 'recipe-litmus',
      draftsDir: tempDir,
      draft: {
        kind: 'experiment',
        recipe: 'litmus-paper-acid-base',
        topic: 'Giấy quỳ tím thử axit và bazơ',
        level: 'THCS',
        skill: 'chem-3d-experiment',
        language: 'vi',
        renderMode: 'threejs',
        scene: {
          apparatus: ['litmus-paper', 'beaker'],
          cameraPreset: 'wide-compare',
          themeVersion: 'chem-lab-dark',
        },
        interaction: {
          primaryMode: 'direct-manipulation',
          goldenPath: ['pick-litmus', 'touch-solution', 'observe-color'],
          resetRequired: true,
          autoplayRequired: true,
        },
        verification: {
          requiresFormat: true,
          requiresSmoke: true,
          requiresCanvas: true,
          requiresInteraction: true,
          requiresVisibility: true,
          requiresOffline: true,
        },
      },
    }),
    /does not have recipe-scene-builder support/
  );
});

test('compileSemanticDraft rejects Cu plus hot concentrated H2SO4 recipe until it has a builder', async () => {
  const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'chem-compile-cu-h2so4-'));
  await assert.rejects(
    compileSemanticDraft({
      slug: 'cu-h2so4-heating',
      draftsDir: tempDir,
      draft: {
        kind: 'experiment',
        recipe: 'cu-h2so4-heating',
        topic: 'Đồng tác dụng với H2SO4 đặc nóng',
        level: 'THPT',
        skill: 'chem-3d-experiment',
        language: 'vi',
        renderMode: 'threejs',
        scene: {
          apparatus: ['copper-piece', 'test-tube', 'alcohol-burner'],
          cameraPreset: 'lab-close',
          themeVersion: 'chem-lab-dark',
        },
        interaction: {
          primaryMode: 'direct-manipulation',
          goldenPath: ['load-copper', 'heat-tube', 'finish-reaction'],
          resetRequired: true,
          autoplayRequired: true,
        },
        verification: {
          requiresFormat: true,
          requiresSmoke: true,
          requiresCanvas: true,
          requiresInteraction: true,
          requiresVisibility: true,
          requiresOffline: true,
        },
      },
    }),
    /does not have recipe-scene-builder support/
  );
});
