import assert from 'node:assert/strict';
import test from 'node:test';

import { auditRecipeSceneContract } from '../scripts/audit-recipe-scene-contract.mjs';

const baseDraft = {
  kind: 'experiment',
  renderMode: 'threejs',
  recipe: 'sugar-h2so4-dehydration',
  scene: {
    apparatus: ['beaker', 'reagent-bottle', 'solid-reagent-jar'],
  },
};

test('recipe scene audit accepts shared free-drag and effect modules', async () => {
  const sceneSource = `
    const drag = createFreeDragController({ camera, renderer, controls });
    drag.registerDraggable({ id: 'acid-bottle', object: bottle.group });
    const stream = createPourStream({ parent: scene });
    const bubbles = createBubbleField({ parent: scene });
    const steam = createSteamField({ parent: scene });
    const sparks = createSparkField({ parent: scene });
    const glow = createGlowRing({ parent: scene });
    const reaction = createDehydrationCarbonizationReaction({
      bubbleField: bubbles,
      steamField: steam,
      sparkField: sparks,
      glowRing: glow,
    });
  `;

  const result = await auditRecipeSceneContract({ draft: baseDraft, sceneSource });
  assert.equal(result.ok, true);
  assert.deepEqual(result.errors, []);
});

test('recipe scene audit rejects scene-local pointer and effect implementations', async () => {
  const sceneSource = `
    renderer.domElement.addEventListener('pointerdown', onPointerDown);
    const bubbleField = new THREE.Points(geometry, material);
    const pourStream = new THREE.Mesh(new THREE.CylinderGeometry(0.05, 0.08, 1), material);
    const glowRing = new THREE.Mesh(new THREE.TorusGeometry(1, 0.04), material);
  `;

  const result = await auditRecipeSceneContract({ draft: baseDraft, sceneSource });
  assert.equal(result.ok, false);
  assert.ok(result.errors.some((error) => /createFreeDragController/.test(error)));
  assert.ok(result.errors.some((error) => /bubble-field/.test(error)));
  assert.ok(result.errors.some((error) => /pour-stream/.test(error)));
  assert.ok(result.errors.some((error) => /glow-ring/.test(error)));
});

test('generated free-drag recipe scenes must expose object overlap completion', async () => {
  const sceneSource = `
    // @generated by scripts/build-recipe-scene.mjs
    const drag = createFreeDragController({ camera, renderer, controls });
    drag.registerDraggable({
      id: 'sample',
      object: sample.group,
      validTargets: [{ anchor: beaker.anchors.effectOrigin, radius: 0.4 }],
    });
    const recipeStepContract = {};
    const recipeCapabilities = {};
    installCoursewareTestHarness({
      getCapabilities() { return recipeCapabilities; },
      getStepContract() { return recipeStepContract; },
    });
  `;
  const result = await auditRecipeSceneContract({
    draft: {
      kind: 'experiment',
      renderMode: 'threejs',
      recipe: 'iron-cuso4-displacement',
    },
    sceneSource,
  });

  assert.equal(result.ok, false);
  assert.ok(result.errors.some((error) => /overlapObject/.test(error)));
  assert.ok(result.errors.some((error) => /overlapPadding/.test(error)));
});

test('zinc/copper comparison scenes must use the classic close comparison apparatus stack', async () => {
  const sceneSource = `
    // @generated by scripts/build-recipe-scene.mjs
    const shell = createSceneShell({ cameraPreset: "lab-close" });
    const recipeStepContract = {};
    const recipeCapabilities = {};
    installCoursewareTestHarness({
      getCapabilities() { return recipeCapabilities; },
      getStepContract() { return recipeStepContract; },
    });
  `;

  const result = await auditRecipeSceneContract({
    draft: {
      kind: 'experiment',
      renderMode: 'threejs',
      recipe: 'zinc-copper-hcl-compare',
    },
    sceneSource,
  });

  assert.equal(result.ok, false);
  assert.ok(result.errors.some((error) => /classic close comparison camera/.test(error)));
  assert.ok(result.errors.some((error) => /classic showcase test-tube apparatus/.test(error)));
});
