import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';

import { compileSemanticDraft } from '../scripts/compile-semantic-draft.mjs';
import {
  buildRecipeSceneArtifact,
  supportsRecipeSceneBuilder,
} from '../scripts/build-recipe-scene.mjs';
import { auditRecipeSceneContract } from '../scripts/audit-recipe-scene-contract.mjs';

const ironRecipe = {
  id: 'iron-cuso4-displacement',
  theme: 'chem-lab-dark',
  cameraPreset: 'lab-close',
  requiredApparatus: ['iron-nail', 'beaker'],
  interaction: 'free-drag-contact',
  reaction: 'metal-displacement',
  effects: ['bubble-field', 'color-transition', 'material-progress'],
  resultSustainEffects: [],
  steps: [
    {
      id: 'place-iron',
      type: 'drag-drop-anchor',
      source: 'iron-nail.gripAnchor',
      sourcePlacementAnchor: 'iron-nail.sampleZone',
      target: 'beaker.effectOrigin',
      targetRadius: 0.78,
      overlapPadding: 0.28,
      placementOffset: [0.04, 0.08, 0.02],
      placementRotation: [0.04, 0, -1.36],
      onComplete: 'start-reaction',
    },
    {
      id: 'finish-reaction',
      type: 'reaction-progress',
      reaction: 'metal-displacement',
      successPhase: 'result',
    },
  ],
  verifier: 'run-reaction-golden-path',
};

const ironDraft = {
  kind: 'experiment',
  recipe: 'iron-cuso4-displacement',
  topic: 'Đinh sắt thả vào dung dịch CuSO4',
  level: 'THCS',
  skill: 'chem-3d-experiment',
  language: 'vi',
  renderMode: 'threejs',
  scene: {
    apparatus: ['iron-nail', 'beaker'],
    cameraPreset: 'lab-close',
    themeVersion: 'chem-lab-dark',
  },
  interaction: {
    primaryMode: 'direct-manipulation',
    goldenPath: ['place-iron', 'observe-copper-coating', 'finish-reaction'],
    resetRequired: true,
    autoplayRequired: true,
  },
  verification: {
    requiresFormat: true,
    requiresSmoke: true,
    requiresCanvas: true,
    requiresInteraction: true,
    requiresVisibility: true,
    requiresOffline: true,
  },
};

const ch4Recipe = {
  id: 'ch4-combustion-flame-test',
  theme: 'chem-lab-dark',
  cameraPreset: 'lab-close',
  requiredApparatus: ['gas-generator', 'gas-delivery-tube', 'test-tube', 'alcohol-burner'],
  interaction: 'free-drag-flame-test',
  reaction: 'methane-combustion',
  effects: ['bubble-field', 'steam-field', 'spark-field', 'glow-ring', 'flame-plume'],
  resultSustainEffects: ['steam-field', 'spark-field', 'glow-ring', 'flame-plume'],
  steps: [
    {
      id: 'release-ch4',
      type: 'drag-pour-anchor',
      source: 'gas-delivery-tube.gripAnchor',
      sourcePlacementAnchor: 'gas-delivery-tube.outletAnchor',
      target: 'test-tube.mouth',
      targetRadius: 0.46,
      overlapPadding: 0.38,
      placementOffset: [0, 0.1, 0],
      placementRotation: [0.08, 0, -0.12],
      onComplete: 'stage-gas',
    },
    {
      id: 'ignite-ch4',
      type: 'drag-heat-anchor',
      source: 'alcohol-burner.flameOrigin',
      sourcePlacementAnchor: 'alcohol-burner.flameOrigin',
      target: 'test-tube.steamOrigin',
      targetRadius: 0.56,
      overlapPadding: 0.24,
      placementOffset: [0.02, -0.1, 0],
      placementRotation: [0, 0, 0],
      onComplete: 'start-reaction',
    },
    {
      id: 'finish-combustion',
      type: 'reaction-progress',
      reaction: 'methane-combustion',
      successPhase: 'result',
    },
  ],
  verifier: 'run-reaction-golden-path',
};

const ch4Draft = {
  kind: 'experiment',
  recipe: 'ch4-combustion-flame-test',
  topic: 'Đốt cháy khí metan CH4',
  level: 'THCS',
  skill: 'chem-3d-experiment',
  language: 'vi',
  renderMode: 'threejs',
  scene: {
    apparatus: ['gas-generator', 'gas-delivery-tube', 'test-tube', 'alcohol-burner'],
    cameraPreset: 'lab-close',
    themeVersion: 'chem-lab-dark',
  },
  interaction: {
    primaryMode: 'direct-manipulation',
    goldenPath: ['release-ch4', 'ignite-ch4', 'finish-combustion'],
    resetRequired: true,
    autoplayRequired: true,
  },
  verification: {
    requiresFormat: true,
    requiresSmoke: true,
    requiresCanvas: true,
    requiresInteraction: true,
    requiresVisibility: true,
    requiresOffline: true,
  },
};

test('recipe scene builder supports the iron CuSO4 recipe and emits generated-only scene code', () => {
  assert.equal(supportsRecipeSceneBuilder('iron-cuso4-displacement'), true);
  assert.equal(supportsRecipeSceneBuilder('sugar-h2so4-dehydration'), false);

  const artifact = buildRecipeSceneArtifact({ draft: ironDraft, recipe: ironRecipe });
  assert.equal(artifact.generatedBy, 'recipe-scene-builder');
  assert.match(artifact.hudSource, /Recipe: iron-cuso4-displacement/);
  assert.match(artifact.sceneSource, /@generated by scripts\/build-recipe-scene\.mjs/);
  assert.match(artifact.sceneSource, /createBeakerApparatus/);
  assert.match(artifact.sceneSource, /createIronNailApparatus/);
  assert.match(artifact.sceneSource, /createFreeDragController/);
  assert.match(artifact.sceneSource, /createMetalDisplacementReaction/);
  assert.match(artifact.sceneSource, /beaker\.anchors\["effectOrigin"\]/);
  assert.match(artifact.sceneSource, /duration: 8\.5/);
  assert.match(artifact.sceneSource, /applyAnchorPlacement\(\{/);
  assert.match(artifact.sceneSource, /createContextualLabelPolicy\(\{/);
  assert.match(artifact.sceneSource, /createGuidedAnchorMotion\(\{/);
  assert.match(artifact.sceneSource, /const recipeStepContract = /);
  assert.match(artifact.sceneSource, /const recipeCapabilities = /);
  assert.match(artifact.sceneSource, /"resultSustainEffects": \[\]/);
  assert.match(artifact.sceneSource, /getCapabilities\(\)/);
  assert.match(artifact.sceneSource, /getStepContract\(\)/);
  assert.match(artifact.sceneSource, /"type": "drag-drop-anchor"/);
  assert.match(artifact.sceneSource, /"type": "reaction-progress"/);
  assert.match(artifact.sceneSource, /"draggables": \[/);
  assert.match(artifact.sceneSource, /registerDraggable\(\{/);
  assert.match(artifact.sceneSource, /overlapObject: beaker\.group/);
  assert.match(artifact.sceneSource, /overlapPadding: 0\.28/);
  assert.match(artifact.sceneSource, /guidedIronMotion\.start\(\)/);
  assert.match(artifact.sceneSource, /guidedIronMotion\.update\(dt\)/);
  assert.match(artifact.sceneSource, /guidedIronMotion\.state\.active/);
  assert.match(artifact.sceneSource, /bubbleField\.update\(dt, now \* 0\.001\)/);
  assert.match(artifact.sceneSource, /controllers\.setLabel\(\{/);
  assert.match(artifact.sceneSource, /const ironNailLabel = \{/);
  assert.match(artifact.sceneSource, /ironNailLabelPolicy\.hide\(\)/);
  assert.match(artifact.sceneSource, /ironNailLabelPolicy\.show\(\)/);
  assert.doesNotMatch(artifact.sceneSource, /const autoplayMotion = \{/);
  assert.doesNotMatch(artifact.sceneSource, /function startAutoplayMotion\(\)/);
  assert.doesNotMatch(artifact.sceneSource, /function updateAutoplayMotion\(dt\)/);
  assert.doesNotMatch(artifact.sceneSource, /function makeIronSolutionPose\(\)/);
  assert.doesNotMatch(artifact.sceneSource, /window\.setTimeout\(\(\) => runVerifierStep\('finish-reaction'\), 1100\)/);
  assert.doesNotMatch(artifact.sceneSource, /autoplayButton\?\.\addEventListener\('click', \(\) => \{\s*runVerifierStep\('place-iron'\)/);
  assert.doesNotMatch(artifact.sceneSource, /\bnew\s+THREE\.(Mesh|BoxGeometry|CylinderGeometry|SphereGeometry|ConeGeometry|TorusGeometry|RingGeometry|CircleGeometry|PlaneGeometry|MeshStandardMaterial|MeshBasicMaterial|MeshPhysicalMaterial|Points|PointsMaterial)\b/);
  assert.doesNotMatch(artifact.sceneSource, /effectOrigin, \[0\.18, 0\.18, 0\.04\]/);
  assert.doesNotMatch(artifact.sceneSource, /createManipulationController/);
  assert.doesNotMatch(artifact.sceneSource, /modelsOverlapOrNear/);
});

test('compileSemanticDraft uses recipe scene builder for iron CuSO4 recipe drafts', async () => {
  const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'chem-recipe-builder-'));
  const output = await compileSemanticDraft({
    slug: 'iron-cuso4-recipe-builder',
    draftsDir: tempDir,
    draft: ironDraft,
  });

  const scene = await fs.readFile(path.join(output.draftsDir, 'iron-cuso4-recipe-builder.scene.js'), 'utf8');
  const meta = JSON.parse(
    await fs.readFile(path.join(output.draftsDir, 'iron-cuso4-recipe-builder.meta.json'), 'utf8'),
  );
  const audit = await auditRecipeSceneContract({ draft: ironDraft, sceneSource: scene, recipe: ironRecipe });

  assert.equal(audit.ok, true, audit.errors.join(', '));
  assert.equal(meta.recipe, 'iron-cuso4-displacement');
  assert.equal(meta.generatedBy, 'recipe-scene-builder');
  assert.match(scene, /source: 'recipe-scene-builder'/);
  assert.match(scene, /getGoldenPath\(\)/);
  assert.match(scene, /getCapabilities\(\)/);
  assert.match(scene, /getStepContract\(\)/);
  assert.match(scene, /dragFromPageApi\(\)/);
  assert.match(scene, /successPhase: "result"/);
});

test('recipe scene builder supports CH4 combustion without scene-local effects', async () => {
  assert.equal(supportsRecipeSceneBuilder('ch4-combustion-flame-test'), true);

  const artifact = buildRecipeSceneArtifact({ draft: ch4Draft, recipe: ch4Recipe });
  const audit = await auditRecipeSceneContract({ draft: ch4Draft, sceneSource: artifact.sceneSource, recipe: ch4Recipe });

  assert.equal(audit.ok, true, audit.errors.join(', '));
  assert.equal(artifact.generatedBy, 'recipe-scene-builder');
  assert.match(artifact.hudSource, /Recipe: ch4-combustion-flame-test/);
  assert.match(artifact.sceneSource, /createGasGeneratorApparatus/);
  assert.match(artifact.sceneSource, /createGasDeliveryTubeApparatus/);
  assert.match(artifact.sceneSource, /createTestTubeApparatus/);
  assert.match(artifact.sceneSource, /createAlcoholBurnerApparatus/);
  assert.match(artifact.sceneSource, /createFlamePlume/);
  assert.match(artifact.sceneSource, /createMethaneCombustionReaction/);
  assert.match(artifact.sceneSource, /"type": "drag-pour-anchor"/);
  assert.match(artifact.sceneSource, /"type": "drag-heat-anchor"/);
  assert.match(artifact.sceneSource, /"type": "reaction-progress"/);
  assert.match(artifact.sceneSource, /"resultSustainEffects": \[/);
  assert.match(artifact.sceneSource, /"flame-plume"/);
  assert.match(artifact.sceneSource, /"methane_delivery_tube"/);
  assert.match(artifact.sceneSource, /"alcohol_burner"/);
  assert.match(artifact.sceneSource, /overlapObject: testTube\.group/);
  assert.match(artifact.sceneSource, /overlapPadding: 0\.38/);
  assert.doesNotMatch(artifact.sceneSource, /\bnew\s+THREE\.(Mesh|BoxGeometry|CylinderGeometry|SphereGeometry|ConeGeometry|TorusGeometry|RingGeometry|CircleGeometry|PlaneGeometry|MeshStandardMaterial|MeshBasicMaterial|MeshPhysicalMaterial|Points|PointsMaterial)\b/);
});
